version: "3.7"

services:

  # appコンテナ
  app:
    container_name: order-lumen
    hostname: order-lumen
    build:
      dockerfile: ./docker/lumen/Dockerfile
      context: .
      target: ${APP_ENV}
    env_file:
      - .env
    image: order-lumen:latest
    tty: true
    volumes:
      - .:/var/www/order
    working_dir: /var/www/order
    networks:
      - default
    depends_on:
      - db

  # webコンテナ
  web:
    container_name: order-nginx
    hostname: order-nginx
    build:
      dockerfile: ./docker/nginx/Dockerfile
      target: ${APP_ENV}
      context: .
    env_file:
      - .env
    image: order-nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/order
    working_dir: /var/www/order
    networks:
      - default
      - shared
    depends_on:
      - app

  # dbコンテナ
  db:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: order-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    hostname: order-mysql
    image: mysql:5.7
    networks:
      - default
    ports:
      - "3303:3306"
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  db_volume:
    driver: local

networks:
  outside:
    external:
      name: shared
