version: "3.7"

services:

  # appコンテナ
  app:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
      target: ${APP_ENV}
    container_name: orchestrator-fastapi
    image: orchestrator-fastapi:latest
    hostname: orchestrator-fastapi
    networks:
      - default
      - shared
    tty: true
    volumes:
      - .:/var/www/orchestrator

networks:
  outside:
    external:
      name: shared
