version: "3.7"

services:

  # appコンテナ
  app:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
      target: ${APP_ENV}
    container_name: orchestrator-fastapi
    image: orchestrator-fastapi:latest
    hostname: orchestrator-fastapi
    networks:
      - default
    tty: true
    volumes:
      - .:/var/www/orchestrator

networks:
  default:
    name: orchestrator-network
