version: "3.7"

services:

  # appコンテナ
  app:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
      target: ${APP_ENV}
    container_name: customer-fastapi
    depends_on:
      - db
    image: customer-fastapi:latest
    hostname: customer-fastapi
    networks:
      - default
      - shared
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/var/www/customer

  # dbコンテナ
  db:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: customer-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    image: mysql:5.7
    hostname: customer-mysql
    ports:
      - "3302:3306"
    networks:
      - default
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  db_volume:
    driver: local

networks:
  shared:
    external: true
