#===================
# Global ARG
#===================
ARG MYSQL_VERSION=5.7
ARG LABEL="Hiroki <hasegawafeedshop@gmail.com>"

#===================
# Base Stage
#===================
FROM mysql:${MYSQL_VERSION}
